language: ruby
rvm:
- 2.3.1
before_install: gem install bundler -v 1.11.2
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: jxMbI/2uK36gnEIxmFgVF5ggUwXS8ehO2grKzxSWSCogwtsMOhiL7J2BWFjzO321tilJuunfuvLTJZYtDrgO3AHgB7mZD9qJG6Iry3IA+TjU/azQreJX2hO5/Ku8SavSPFfqCA6ypSOekrHUR3Y9jD2MTDlML7t3eL/6YrecViWfe5X5MaYbTEgarThPFCOtphJajX0y24t6zPMyjCuxJX+QIorMk4w09lKC4PAyzhoYyA4YFNfa9I4Rb20cUhMKNheMwvhHtdjDscHnvXsyM/V9cPk8WB34TCaLFnpK4/DCqzd6agNPbA/jEkI3sBhoVR5SM3mxhcFCvqs3UrPNRCZ6l5uDMwILYskGkzqVhiHAAXlvxhnO0ZDkamTi52iT9aia6eKMPp9sjh//e0113181XLrOI43Kc39xvq86rq2Mpvbk/JgiYYLM4/7Naer9I9kVSBIxY0r4MLkO3ukXu6dRv4VZqXg+/Pzxy1tjS7i0SGhmtog7NCDOBYPvrKzgAMryJoh62xFavQUC95Wv6Xr0MT5wxytNrBs1iB4q914PTAAKt5aQVVlIFTv7rTqaRb70zgvkL6sfRfzrGUGrPHzTFVMJkydk5JX7U12Wxuyx9pQyHcM6WG90TiDMzpTCwMcU45MjpHnhPLGcLVO6K9zgLDoJgsbrXdA0a71Uh7Y=
